# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cbagdon <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/07 13:27:46 by cbagdon           #+#    #+#              #
#    Updated: 2018/11/07 13:30:21 by cbagdon          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRC = srcs/ft_display_file.c

all:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)

clean:
	rm -rf *.o

fclean:	clean
	rm -rf $(NAME)

re:	fclean all
