# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cbagdon <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/07 16:05:54 by cbagdon           #+#    #+#              #
#    Updated: 2018/11/07 16:07:49 by cbagdon          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FILE = ft_cat
SRCS = srcs/cat.c

all:
	gcc -o $(FILE) $(SRCS)

clean:
	rm -rf *.o

fclean:	clean
	rm -rf $(FILE)

re:	fclean all
